import click
import orjson

from embedtrain.embed_skels import EMBED_SKELS


def default(obj):
    if isinstance(obj, set):
        return list(obj)
    raise TypeError


@click.command()
@click.argument("outf", type=click.File("wb"))
def export(outf):
    dump = {
        "__WARNING__": "This file is automatically generated by skelshop --- please do not manually edit!"
    }
    for skel_name, skel_type in EMBED_SKELS.items():
        dump[skel_name] = skel_type.export()
    outf.write(orjson.dumps(dump, option=orjson.OPT_NON_STR_KEYS, default=default))


if __name__ == "__main__":
    export()
